language: go
sudo: false

go:
  - 1.x
  - master

install:
  - go get github.com/boltdb/bolt
  - go get github.com/gorilla/mux
  - go get github.com/gorilla/securecookie
  - go get github.com/gorilla/sessions
  - go get github.com/microcosm-cc/bluemonday
  - go get github.com/opennota/dkv
  - go get github.com/opennota/morph
  - go get github.com/opennota/substring
  - go get github.com/PuerkitoBio/goquery
  - go get golang.org/x/net/html/charset
  - go build ./...

script:
  - test -z "$(gofmt -l . | tee /dev/stderr)"
  - go test -v ./...

